export enum TeamName {
  ADELAIDE = 'Adelaide',
  BRISBANE = 'Brisbane Lions',
  CARLTON = 'Carlton',
  COLLINGWOOD = 'Collingwood',
  ESSENDON = 'Essendon',
  FREMANTLE = 'Fremantle',
  GOLD_COAST = 'Gold Coast',
  GWS = 'Greater Western Sydney',
  HAWTHORN = 'Hawthorn',
  MELBOURNE = 'Melbourne',
  NORTH_MELBOURNE = 'North Melbourne',
  PORT_ADELAIDE = 'Port Adelaide',
  RICHMOND = 'Richmond',
  ST_KILDA = 'St Kilda',
  SYDNEY = 'Sydney',
  WEST_COAST = 'West Coast',
  WESTERN_BULLDOGS = 'Western Bulldogs',
}

export const TEAM_NAMES = [
  TeamName.ADELAIDE,
  TeamName.BRISBANE,
  TeamName.CARLTON,
  TeamName.COLLINGWOOD,
  TeamName.ESSENDON,
  TeamName.FREMANTLE,
  TeamName.GOLD_COAST,
  TeamName.GWS,
  TeamName.HAWTHORN,
  TeamName.MELBOURNE,
  TeamName.NORTH_MELBOURNE,
  TeamName.PORT_ADELAIDE,
  TeamName.RICHMOND,
  TeamName.ST_KILDA,
  TeamName.SYDNEY,
  TeamName.WEST_COAST,
  TeamName.WESTERN_BULLDOGS,
]