CREATE TABLE IF NOT EXISTS roundstats (
  playerid                  VARCHAR(100) NOT NULL,
  game                      INT,
  opponent                  VARCHAR(255),
  roundNumber               VARCHAR(10),
  result                    VARCHAR(10),
  jumperNumber              INT,
  kicks                     INT,
  marks                     INT,
  handballs                 INT,
  disposals                 INT,
  goals                     INT,
  behinds                   INT,
  hitouts                   INT,
  tackles                   INT,
  rebound50s                INT,
  inside50s                 INT,
  clearances                INT,
  clangers                  INT,
  freekicksFor              INT,
  freekicksAgainst          INT,
  brownlowVotes             INT,
  contestedPossessions      INT,
  uncontestedPossessions    INT,
  contestedMarks            INT,
  marksInside50             INT,
  onepercenters             INT,
  bounces                   INT,
  goalAssists               INT,
  timeOnGroundPercentage    INT,
  PRIMARY KEY (playerid, game),
  FOREIGN KEY (playerid) REFERENCES player(id)
);
