import { BASE_AFL_TABLES_URL, PLAYER_STATS_PATH } from "../constants/url"

export type RoundStats = {
  game: number,
  team: string,
  opponent: string,
  roundNumber: string,
  year: number,
  result: string,
  jumperNumber: number,
  kicks: number,
  marks: number,
  handballs: number,
  disposals: number,
  goals: number,
  behinds: number,
  hitouts: number,
  tackles: number,
  rebound50s: number,
  inside50s: number,
  clearances: number,
  clangers: number,
  freekicksFor: number,
  freekicksAgainst: number,
  brownlowVotes: number,
  contestedPossessions: number,
  uncontestedPossessions: number,
  contestedMarks: number,
  marksInside50: number,
  onepercenters: number,
  bounces: number,
  goalAssists: number,
  timeOnGroundPercentage: number,
}

export const playerIdToLink = (playerId: string): string => {
  const initial = playerId.charAt(0).toUpperCase()
  return `${BASE_AFL_TABLES_URL}${PLAYER_STATS_PATH}/${initial}/${playerId}.html`
}

export const rawDataToRoundStats = (data: string[], team: string, year: number): RoundStats => ({
  game: Number(data[0]),
  opponent: data[1],
  roundNumber: data[2],
  result: data[3],
  jumperNumber: Number(data[4]),
  kicks: Number(data[5]),
  marks: Number(data[6]),
  handballs: Number(data[7]),
  disposals: Number(data[8]),
  goals: Number(data[9]),
  behinds: Number(data[10]),
  hitouts: Number(data[11]),
  tackles: Number(data[12]),
  rebound50s: Number(data[13]),
  inside50s: Number(data[14]),
  clearances: Number(data[15]),
  clangers: Number(data[16]),
  freekicksFor: Number(data[17]),
  freekicksAgainst: Number(data[18]),
  brownlowVotes: Number(data[19]),
  contestedPossessions: Number(data[20]),
  uncontestedPossessions: Number(data[21]),
  contestedMarks: Number(data[22]),
  marksInside50: Number(data[23]),
  onepercenters: Number(data[24]),
  bounces: Number(data[25]),
  goalAssists: Number(data[26]),
  timeOnGroundPercentage: Number(data[27]),
  team,
  year,
})

export const roundStatsToPostgres = (stats: RoundStats) => ([
  stats.game,
  stats.team,
  stats.opponent,
  stats.roundNumber,
  stats.year,
  stats.result,
  stats.jumperNumber,
  stats.kicks,
  stats.marks,
  stats.handballs,
  stats.disposals,
  stats.goals,
  stats.behinds,
  stats.hitouts,
  stats.tackles,
  stats.rebound50s,
  stats.inside50s,
  stats.clearances,
  stats.clangers,
  stats.freekicksFor,
  stats.freekicksAgainst,
  stats.brownlowVotes,
  stats.contestedPossessions,
  stats.uncontestedPossessions,
  stats.contestedMarks,
  stats.marksInside50,
  stats.onepercenters,
  stats.bounces,
  stats.goalAssists,
  stats.timeOnGroundPercentage,
])
